import React, { useEffect } from 'react';

export default function Preview({ data }) {
    if (!data || !data.previewUrl) {
        return <div className="text-gray-400 text-sm">Preview Empty</div>;
    }

    // The printer prints vertically usually (D30), but we often visualize horizontally.
    // However, the data sent is usually "width" across the printhead.
    // For D30, width is fixed (usually 384 dots).
    // The image url generated by our processor is already properly sized.

    return (
        <img
            src={data.previewUrl}
            alt="Print Preview"
            className="max-w-full object-contain filter grayscale"
            style={{ imageRendering: 'pixelated' }}
        />
    );
}
